apiVersion: v1 
kind: Namespace 
metadata:
  name: swiggy
---
apiVersion: v1 
kind: Secret 
metadata:
  name: db-secret
  namespace: swiggy
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eXVrdGhh
  MYSQL_USER: dmVua3k=
  MYSQL_PASSWORD: dmVua3k=
---
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: db-config 
  namespace: swiggy
data: 
  DB_HOST: "swiggy-db-svc"
  DB_PORT: "3306"
  DB_NAME: "swiggy_lite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: swiggy
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: swiggy-db
  namespace: swiggy
spec:
  replicas: 2
  updateStrategy:
    type: RollingUpdate 
  serviceName: swiggy-db-svc
  selector:
    matchLabels:
      db: swiggy
  template:
    metadata:
      labels:
        db: swiggy
    spec:
      containers:
        - name: swiggy-container
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: sql-port
          imagePullPolicy: Always
          restartPolicy: OnFailure
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: db-secret
                   key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
          volumeMounts:
            - name: pvc 
              mountPath: /swiggy/data
              readOnly: false
      volumes:
        - name: pvc 
          persistentVolumeClaim:
            claimName: db-pvc   
---
apiVersion: v1 
kind: Service 
metadata: 
  name: swiggy-db-svc
  namespace: swiggy
spec:
  clusterIP: None
  ports:
    - name: sql
      port: 3306
      targetPort: sql-port
      protocol: TCP
  selector:
    db: swiggy
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: swiggy-deployy
  namespace: swiggy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate 
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: swiggy
          image: venkaiahk/swiggy:v3
          ports:
            - containerPort: 5603
          resources:
            requests:
              cpu: "300m"
              memory: "600Mi"
            limits:
              cpu: "400m"
              memory: "800Mi"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
---
apiVersion: v1 
kind: Service 
metadata:
  name: app-svc
  namespace: swiggy
spec:
  selector: 
    app: swiggy
  ports:
    - name: app-port
      port: 80
      targetPort: 5603
      protocol: TCP
      nodePort: 32000
  type: NodePort
